# Form implementation generated from reading ui file 'files/main_window/gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_{{ obj_name }}(object):
    def setupUi(self, {{ obj_name }}):
        {{ obj_name }}.setObjectName("{{ obj_name }}")
        {{ obj_name }}.resize(1094, 709)
        self.centralwidget = QtWidgets.QWidget(parent={{ obj_name }})
        self.centralwidget.setObjectName("centralwidget")
        {{ obj_name }}.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent={{ obj_name }})
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1094, 20))
        self.menubar.setObjectName("menubar")
        {{ obj_name }}.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent={{ obj_name }})
        self.statusbar.setObjectName("statusbar")
        {{ obj_name }}.setStatusBar(self.statusbar)

        self.retranslateUi({{ obj_name }})
        QtCore.QMetaObject.connectSlotsByName({{ obj_name }})

    def retranslateUi(self, {{ obj_name }}):
        _translate = QtCore.QCoreApplication.translate
        {{ obj_name }}.setWindowTitle(_translate("{{ obj_name }}", "{{ window_title }}"))
