# Form implementation generated from reading ui file 'files/dialog_window/gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_{{ obj_name }}(object):
    def setupUi(self, {{ obj_name }}):
        {{ obj_name }}.setObjectName("{{ obj_name }}")
        {{ obj_name }}.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent={{ obj_name }})
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi({{ obj_name }})
        self.buttonBox.accepted.connect({{ obj_name }}.Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect({{ obj_name }}.Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName({{ obj_name }})

    def retranslateUi(self, {{ obj_name }}):
        _translate = QtCore.QCoreApplication.translate
        {{ obj_name }}.setWindowTitle(_translate("{{ obj_name }}", "{{ window_title }}"))
