# Form implementation generated from reading ui file 'files/widget/gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_{{ obj_name }}(object):
    def setupUi(self, {{ obj_name }}):
        {{ obj_name }}.setObjectName("{{ obj_name }}")
        {{ obj_name }}.resize(400, 300)

        self.retranslateUi({{ obj_name }})
        QtCore.QMetaObject.connectSlotsByName({{ obj_name }})

    def retranslateUi(self, {{ obj_name }}):
        _translate = QtCore.QCoreApplication.translate
        {{ obj_name }}.setWindowTitle(_translate("{{ obj_name }}", "{{ window_title }}"))
